title:              Team Off
email:              TeamOffPublic@gmail.com
description:        Blog
author:             Team Off
baseurl:            ""
url:                "https://TeamOffPublic.github.io"

# Social Profiles
twitter_username:
github_username:    TeamOffPublic
facebook_username:
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:    # out your google-analytics code

# Build settings
markdown:           kramdown
highlighter:        rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

sass: 
  sass_dir: _sass 
  style: :compressed